#!/usr/bin/env python3

import re

with open("javascript/src/season.js", "r+", encoding="utf-8") as file:
    content = file.read()

    if "return Animal.Feature" in content:
        content = re.sub("Animal.Feature", "Animal.Improvement", content)
        SEASON = "Improvement"
    else:
        content = re.sub("Animal.Improvement", "Animal.Feature", content)
        SEASON = "Feature"

    file.seek(0)
    file.write(content)
    file.truncate()

print(f"::set-output name=season::{SEASON}")
